import Route from '@ember/routing/route';

export default Route.extend({
	model() {
		return [{
			id: '霉素',
			type: "口服抗生素",
			treatmentarea: "抗生素",
			selltime: "2000",
			medicalinsurance: "甲类",
			development: "首仿",
			companyprice: 46,
		}, {
			id: "霉素",
			type: "口服抗生素",
			treatmentarea: "抗生素",
			selltime: "2000",
			medicalinsurance: "甲类",
			development: "首仿",
			companyprice: 88,
		}, {
			id: "霉素",
			type: "口服抗生素",
			treatmentarea: "抗生素",
			selltime: "2000",
			medicalinsurance: "甲类",
			development: "首仿",
			companyprice: 95,
		}, {
			id: "霉素",
			type: "口服抗生素",
			treatmentarea: "抗生素",
			selltime: "2000",
			medicalinsurance: "甲类",
			development: "首仿",
			companyprice: 26,
		}, {
			id: "霉素",
			type: "口服抗生素",
			treatmentarea: "抗生素",
			selltime: "2000",
			medicalinsurance: "甲类",
			development: "首仿",
			companyprice: 45,
		}, {
			id: "霉素",
			type: "口服抗生素",
			treatmentarea: "抗生素",
			selltime: "2000",
			medicalinsurance: "甲类",
			development: "首仿",
			companyprice: 87,
		}, {
			id: "霉素",
			type: "口服抗生素",
			treatmentarea: "抗生素",
			selltime: "2000",
			medicalinsurance: "甲类",
			development: "首仿",
			companyprice: 456,
		}, {
			id: "霉素",
			type: "口服抗生素",
			treatmentarea: "抗生素",
			selltime: "2000",
			medicalinsurance: "甲类",
			development: "首仿",
			companyprice: 4565,
		}, {
			id: "霉素",
			type: "口服抗生素",
			treatmentarea: "抗生素",
			selltime: "2000",
			medicalinsurance: "甲类",
			development: "首仿",
			companyprice: 2,
		}, {
			id: "霉素",
			type: "口服抗生素",
			treatmentarea: "抗生素",
			selltime: "2000",
			medicalinsurance: "甲类",
			development: "首仿",
			companyprice: 144,
		}];
	}
});